language: node_js
before_script:
  - npm install grunt-cli -g
  - npm install bower -g
  - bower install
  - chmod -x deploy.sh
script:
  - grunt build
deploy:
  provider: script
  script: ./deploy.sh
